model: openai/gpt-5
editor-model: openai/gpt-5
auto-commits: true
commit-prompt: |
  Кратко и по делу. Формат:
  - scope: <подсистема>
  - what: <что сделано>
  - why: <зачем/эффект>

# чтобы Aider видел важные файлы по умолчанию
read:
  - README.md
  - Procfile
  - requirements.txt
  - app/**/*.py
  - config/**/*.yaml

# стиль кода
lint-cmd: "ruff check --fix . && black ."
