books:
  - id: "atomic_habits"
    title: "Атомные привычки"
    author: "Джеймс Клир"
    status: "in_work"
    gdrive_file_id: "1taFfjvLDqMPBRdQ_S41o08jsXfCjJNCm_mVsJZkG8Po"   # скопируй из своей ссылки
