channels:
  - name: ChitaiDelai           # ← ЭТО НУЖНО ДЛЯ ТЕКУЩЕГО main.py
    alias: "@chitaidelai"
    token_env: BOT_TOKEN_CHITAI
    timezone: "Europe/Moscow"
    enabled: true

    # эти поля на будущее (не мешают текущему коду)
    provider: "telegram"
    chat_id: "6847953293"
