channels:
  - name: "ChitaiDelai"
    alias: "@chitaidelai"
    token_env: "BOT_TOKEN_CHITAI"
    timezone: "Europe/Moscow"
    enabled: true

    # пока не используются
    provider: "telegram"
    chat_id: "6847953293"
