channels:
  - id: "tg:chitaidelai"
    provider: "telegram"
    chat_id: "6847953293"
    token_env: BOT_TOKEN_CHITAI
    timezone: "Europe/Moscow"
    enabled: true
    schedule:
      - cron: "*/2 * * * *"   # каждые 2 минуты для теста
        pipeline: ["generate", "publish"]
