timezone: Europe/Moscow

channels:
  - alias: chitaidelai
    name: "@chitaidelai"
    slots:
      - format: "announce"
        time: "08:30"
      - format: "insight"
        time: "11:00"
      - format: "practice"
        time: "12:45"
      - format: "case"
        time: "16:00"
      - format: "quote"
        time: "18:30"
      - format: "reflect"
        time: "21:00"
