timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "17:44"
      - format: "insight"
        time: "17:45"
      - format: "practice"
        time: "17:46"
      - format: "case"
        time: "17:47"
      - format: "quote"
        time: "17:48"
      - format: "reflect"
        time: "17:49"
