timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "13:40"
      - format: "insight"
        time: "14:00"
      - format: "practice"
        time: "16:00"
      - format: "case"
        time: "18:00"
      - format: "quote"
        time: "20:30"
      - format: "reflect"
        time: "23:00"
