timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "16:16"
      - format: "insight"
        time: "16:17"
      - format: "practice"
        time: "16:18"
      - format: "case"
        time: "16:19"
      - format: "quote"
        time: "16:20"
      - format: "reflect"
        time: "16:21"
