timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "17:00"
      - format: "insight"
        time: "17:01"
      - format: "practice"
        time: "17:02"
      - format: "case"
        time: "17:03"
      - format: "quote"
        time: "17:04"
      - format: "reflect"
        time: "17:05"
