timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "15:20"
      - format: "insight"
        time: "15:21"
      - format: "practice"
        time: "15:22"
      - format: "case"
        time: "15:23"
      - format: "quote"
        time: "15:24"
      - format: "reflect"
        time: "15:25"
