timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "12:10"
      - format: "insight"
        time: "11:59"
      - format: "practice"
        time: "13:59"
      - format: "case"
        time: "15:59"
      - format: "quote"
        time: "17:59"
      - format: "reflect"
        time: "19:58"
