default_tz: Europe/Moscow

slots:
  ChitaiDelai:
    - time: "09:00"
      format: "quote"

    - time: "12:10"
      format: "summary5"

    - time: "17:02"
      format: "practice"

    - time: "20:04"
      format: "card"
