timezone: Europe/Moscow

channels:
  - alias: chitaidelai
    name: "@chitaidelai"
    slots:
      - format: "announce"
        time: "13:03"   # тест-прокол прямо сейчас
      - format: "insight"
        time: "14:00"
      - format: "practice"
        time: "16:00"
      - format: "case"
        time: "18:00"
      - format: "quote"
        time: "20:30"
      - format: "reflect"
        time: "23:00"
