timezone: Europe/Moscow

channels:
  - name: "ChitaiDelai"      # совпадает с name в channels.yaml
    alias: "@chitaidelai"    # совпадает с alias в channels.yaml
    slots:
      - format: "announce"
        time: "14:48"
      - format: "insight"
        time: "14:49"
      - format: "practice"
        time: "14:50"
      - format: "case"
        time: "14:51"
      - format: "quote"
        time: "14:52"
      - format: "reflect"
        time: "14:53"
