default_tz: Europe/Moscow

slots:
  ChitaiDelai:
    - time: "09:00"
      format: "quote"

    - time: "13:30"
      format: "summary5"

    - time: "18:09"
      format: "practice"

    - time: "20:04"
      format: "card"
