channels:
  ChitaiDelai:
    tone: |
      Пиши энергично, по делу, без воды. Короткие ясные фразы. Минимум канцелярита.
      Заголовок — крючок. Эмодзи допустимы, но не перегружай.
    formats:
      quote:
        max_len: 350
        instructions: |
          Дай одну сильную цитату из книги (без копипаста длинных кусков), укажи автора/книгу в конце.
          Если цитата длинная — сократи и переформулируй. 1–2 строки, не более.
      core:
        max_len: 600
        instructions: |
          Сформулируй главную мысль книги за 2–4 коротких предложения. Без лишних примеров.
          Добавь мини‑контекст: в чём сила подхода автора.
      insight:
        max_len: 900
        instructions: |
          Объясни, почему это работает. 2–3 абзаца. Избегай общих фраз, дай конкретику.
          В конце — 1 вопрос читателю для вовлечения.
      practice:
        max_len: 800
        instructions: |
          Дай практический чек‑лист по шагам (3–6 пунктов). Короткие императивы.
          Заверши одной финальной фразой‑усилителем (без хэштегов).
