channels:
  ChitaiDelai:
    tone: |
      Пиши энергично, по делу, без воды. Короткие ясные фразы. Минимум канцелярита.
      Заголовок — крючок. Эмодзи допустимы, но не перегружай.
    formats:
      announce:
        max_len: 700
        instructions: |
          О чём книга, для кого, какую пользу обещает. 3–5 предложений. Без спойлеров, без воды.
      core:
        max_len: 600
        instructions: |
          Сформулируй главную мысль книги за 2–4 коротких предложения. Добавь мини‑контекст: в чём сила подхода.
      insight:
        max_len: 900
        instructions: |
          Почему это работает: 2–3 абзаца с причинно‑следственными идеями. В конце — 1 вопрос читателю.
      practice:
        max_len: 800
        instructions: |
          Чек‑лист 3–6 шагов. Короткие императивы. В конце — одна финальная фраза‑усилитель.
      case:
        max_len: 800
        instructions: |
          Короткий пример/мини‑история применения идеи. Что сделали → какой результат → чему это учит.
      quote:
        max_len: 350
        instructions: |
          Одна сильная цитата/формулировка автора (перескажи, если длинная). В конце — автор и книга.
      reflect:
        max_len: 700
        instructions: |
          2–3 мысли об ошибках и препятствиях при внедрении идей книги. Заверши вопросом для вовлечения.
